"""hallazgos

Revision ID: 45061668d69b
Revises: 6cb6ae31ebbb
Create Date: 2026-04-10 11:15:21.675668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45061668d69b'
down_revision: Union[str, Sequence[str], None] = '6cb6ae31ebbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('observacion', sa.String(), nullable=True))
    op.drop_column('evaluaciones', 'comentario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('comentario', sa.VARCHAR(), nullable=True))
    op.drop_column('evaluaciones', 'observacion')
    # ### end Alembic commands ###
